### ISSUE TITLE
Coordinates system relative to canonical window size

### ISSUE THREAD

**Issue by kbok** [bananu7/Hate#14]
When changing the config to set a window size different than 1024x768, loaded sprites and absolute sprite coordinates get resized to an amount relative to the window size.
Maybe read orthoScreenMat from the config?

**Comment by bananu7** [comment]
This is closely related to #2, as in the coordinate calculations are pretty bad right now. Certainly going to look at it somewhere in near future. 

Getting the matrix to use raw resolution from the config sounds like an easy workaround, though.

**Comment by bananu7** [comment]
This also totally confuses the mouse input, as it uses window pixel coordinates starting at top-left.

**Comment by bananu7** [comment]
Fixed in v0.1.3.0.
