### ISSUE TITLE
Missing `image.png` in sample2

### ISSUE THREAD

**Issue by Jefffrey** [bananu7/Hate#3]
Sample2, coming from a fresh install, is missing `image.png` and is therefore failing with:

> "image.png: openBinaryFile: does not exist (No such file or directory)"

**Comment by bananu7** [comment]
This could be any image; I put it there for test purposes, but IIRC never got it to work.

**Comment by bananu7** [comment]
Up for discussion whether images for samples should be commited to the repository.

**Comment by bananu7** [comment]
Necessary assets are now in the repository as of **e144cab**.
